# Generated by Django 5.0.2 on 2024-04-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='item_name',
        ),
    ]
