# Generated by Django 5.0.2 on 2024-04-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_customer_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
    ]
